### ISSUE TITLE
Linear Progress Indicator wraps to two lines in sidebar

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web-catalog#105]
<img width="1221" alt="screen shot 2018-05-03 at 9 36 32 am" src="https://user-images.githubusercontent.com/4703432/39590355-85a6980c-4eb5-11e8-92c7-1b601a75ffd3.png">

**Comment by patrickrodee** [comment]
Related to #106

**Comment by patrickrodee** [comment]
Will be resolved by using a Drawer in #106

**Comment by patrickrodee** [comment]
Closed in #136
