### ISSUE TITLE
Mobile view of a component catalog page should hide the sidebar

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web-catalog#106]
Right now the sidebar ends up at the top of the screen

<img width="378" alt="screen shot 2018-05-03 at 9 39 02 am" src="https://user-images.githubusercontent.com/4703432/39590483-e3b06c20-4eb5-11e8-8d54-f3acc1ea8abb.png">

And all the actual content is pushed down to the bottom
<img width="401" alt="screen shot 2018-05-03 at 9 39 10 am" src="https://user-images.githubusercontent.com/4703432/39590486-e4e2d754-4eb5-11e8-8615-922400e4ec98.png">

**Comment by patrickrodee** [comment]
Closed in #136
