### ISSUE TITLE
Catalog title is too long for mobile screens

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web-catalog#146]
Title is cut off 
![screenshot_20180508-210001](https://user-images.githubusercontent.com/34519388/39795159-212e852c-5303-11e8-8f81-7a7d8b2b8062.png)

**Comment by kfranqueiro** [comment]
Should we consider conditionally showing/hiding "MDC Web" for smaller width screens and the full title for larger?

**Comment by williamernest** [comment]
"MDC Web" for small screens (<= 599px) and "Material Components for the Web" for everything else.
