### ISSUE TITLE
Cal widget

### ISSUE THREAD

**Issue by gedw99** [material-components/material-components-web-catalog#160]
Any chance of any calendar widgets ?

**Comment by kfranqueiro** [comment]
Calendar widgets aren't currently in Material's short-term [roadmap](https://github.com/material-components/material-components/blob/develop/ROADMAP.md). AFAIK, the design team wants to further re-evaluate date and time controls before committing to a design.

PS: feature requests for components should really go in the main [MDC Web](https://github.com/material-components/material-components-web) repository. This repository is specifically for the catalog which demonstrates the components implemented in MDC Web.

I'm going to close this, but we'll definitely open issues related to this at a time when designs are ready to be implemented.
