### ISSUE TITLE
text field shape is broken

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-catalog#212]
<img width="299" alt="screen shot 2018-09-27 at 15 47 43" src="https://user-images.githubusercontent.com/579873/46178695-bd1f4600-c26c-11e8-934f-bb848c1df5ba.png">

**Comment by abhiomkar** [comment]
This is being tracked here [material-components-web/issues/3158](https://github.com/material-components/material-components-web/issues/3158).
