### ISSUE TITLE
Enhanced Select Dropdown alignment is off

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web-catalog#266]
**Version**

v0.44.1

**Actual**

![image](https://user-images.githubusercontent.com/47312/53504266-9e251a00-3a7f-11e9-879d-e678dd719790.png)

**Expected**

![image](https://user-images.githubusercontent.com/47312/53504284-a715eb80-3a7f-11e9-8f41-90d603926f0e.png)

Dropdown is aligned as expected when opened second time.

**Comment by bonniezhou** [comment]
Fixed!
