### ISSUE TITLE
Update Full Width Text Field Demos

### ISSUE THREAD

**Issue by qs-labs** [material-components/material-components-web-catalog#271]
(referencing [material-components-web-react #380](https://github.com/material-components/material-components-web-react/issues/380))

Both Full Width Text Field demos are preserving labels, a behavior no longer supported (see [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#full-width)).

![image](https://user-images.githubusercontent.com/38405319/59369414-64b2aa80-8d0e-11e9-85e0-8d973605fd57.png)

**Comment by bonniezhou** [comment]
Hey @qs-labs - what do you mean by preserving labels? 

In the screenshot, the first text field is not using `mdc-floating-label`, as documented. The second is a full-width _textarea_, which does not have the same restrictions as a full-width text field.

**Comment by qs-labs** [comment]
Hi @bonniezhou - thanks for the clarification. I recently discovered the ability to apply a label to a full-width text field by adding it to the `<input />` element directly; previously, I had mistakenly identified the full-width label as an `mdc-floating-label`. With regards to the _textarea_, it seems I misunderstood the documentation. My apologies for not closing this one earlier!
